; ===================================================================
; Generated by Axiom Freestanding Windows x86-64 Compiler
; Zero CRT - Pure Kernel32.dll target (Reentrant Stack Frames)
; ===================================================================
default rel

extern GetStdHandle
extern WriteFile
extern ExitProcess
extern GetProcessHeap
extern HeapAlloc
extern HeapFree

section .data
const_1e6:  dq 1000000.0
const_half: dq 0.5
str_true:   db 'yes', 0
str_false:  db 'no', 0
crlf:       db 13, 10, 0

str_lit_0: db 61, 61, 61, 32, 65, 120, 105, 111, 109, 32, 83, 116, 114, 101, 115, 115, 32, 84, 101, 115, 116, 32, 52, 58, 32, 83, 116, 114, 105, 110, 103, 115, 32, 105, 110, 32, 65, 114, 114, 97, 121, 115, 32, 38, 32, 76, 101, 116, 116, 101, 114, 32, 73, 110, 100, 101, 120, 105, 110, 103, 32, 61, 61, 61, 0
str_lit_1: db 45, 45, 45, 32, 84, 101, 115, 116, 32, 49, 58, 32, 65, 114, 114, 97, 121, 32, 111, 102, 32, 83, 116, 114, 105, 110, 103, 32, 80, 111, 105, 110, 116, 101, 114, 115, 32, 45, 45, 45, 0
str_lit_2: db 99, 111, 109, 112, 105, 108, 101, 114, 0
str_lit_3: db 102, 114, 101, 101, 115, 116, 97, 110, 100, 105, 110, 103, 0
str_lit_4: db 97, 115, 115, 101, 109, 98, 108, 121, 0
str_lit_5: db 109, 97, 99, 104, 105, 110, 101, 0
str_lit_6: db 119, 111, 114, 100, 115, 91, 48, 93, 58, 0
str_lit_7: db 119, 111, 114, 100, 115, 91, 49, 93, 58, 0
str_lit_8: db 119, 111, 114, 100, 115, 91, 50, 93, 58, 0
str_lit_9: db 119, 111, 114, 100, 115, 91, 51, 93, 58, 0
str_lit_10: db 76, 101, 110, 103, 116, 104, 32, 111, 102, 32, 119, 111, 114, 100, 115, 91, 48, 93, 32, 40, 39, 99, 111, 109, 112, 105, 108, 101, 114, 39, 32, 45, 62, 32, 69, 120, 112, 101, 99, 116, 101, 100, 32, 56, 41, 58, 0
str_lit_11: db 76, 101, 110, 103, 116, 104, 32, 111, 102, 32, 119, 111, 114, 100, 115, 91, 49, 93, 32, 40, 39, 102, 114, 101, 101, 115, 116, 97, 110, 100, 105, 110, 103, 39, 32, 45, 62, 32, 69, 120, 112, 101, 99, 116, 101, 100, 32, 49, 50, 41, 58, 0
str_lit_12: db 62, 62, 32, 80, 65, 83, 83, 58, 32, 83, 116, 114, 105, 110, 103, 32, 65, 114, 114, 97, 121, 32, 83, 116, 111, 114, 97, 103, 101, 32, 38, 32, 76, 101, 110, 103, 116, 104, 32, 67, 97, 108, 99, 117, 108, 97, 116, 105, 111, 110, 32, 86, 101, 114, 105, 102, 105, 101, 100, 0
str_lit_13: db 62, 62, 32, 70, 65, 73, 76, 58, 32, 83, 116, 114, 105, 110, 103, 32, 65, 114, 114, 97, 121, 32, 76, 101, 110, 103, 116, 104, 32, 77, 105, 115, 109, 97, 116, 99, 104, 0
str_lit_14: db 45, 45, 45, 32, 84, 101, 115, 116, 32, 50, 58, 32, 67, 104, 97, 114, 97, 99, 116, 101, 114, 45, 76, 101, 118, 101, 108, 32, 73, 110, 100, 101, 120, 105, 110, 103, 32, 73, 110, 115, 105, 100, 101, 32, 65, 114, 114, 97, 121, 32, 87, 111, 114, 100, 115, 32, 45, 45, 45, 0
str_lit_15: db 70, 105, 114, 115, 116, 32, 108, 101, 116, 116, 101, 114, 32, 111, 102, 32, 119, 111, 114, 100, 115, 91, 48, 93, 32, 40, 65, 83, 67, 73, 73, 32, 111, 102, 32, 39, 99, 39, 44, 32, 69, 120, 112, 101, 99, 116, 101, 100, 32, 57, 57, 41, 58, 0
str_lit_16: db 83, 101, 99, 111, 110, 100, 32, 108, 101, 116, 116, 101, 114, 32, 111, 102, 32, 119, 111, 114, 100, 115, 91, 48, 93, 32, 40, 65, 83, 67, 73, 73, 32, 111, 102, 32, 39, 111, 39, 44, 32, 69, 120, 112, 101, 99, 116, 101, 100, 32, 49, 49, 49, 41, 58, 0
str_lit_17: db 76, 97, 115, 116, 32, 108, 101, 116, 116, 101, 114, 32, 111, 102, 32, 119, 111, 114, 100, 115, 91, 48, 93, 32, 40, 65, 83, 67, 73, 73, 32, 111, 102, 32, 39, 114, 39, 44, 32, 69, 120, 112, 101, 99, 116, 101, 100, 32, 49, 49, 52, 41, 58, 0
str_lit_18: db 62, 62, 32, 80, 65, 83, 83, 58, 32, 73, 110, 100, 105, 118, 105, 100, 117, 97, 108, 32, 67, 104, 97, 114, 97, 99, 116, 101, 114, 32, 73, 110, 100, 101, 120, 105, 110, 103, 32, 86, 101, 114, 105, 102, 105, 101, 100, 0
str_lit_19: db 62, 62, 32, 70, 65, 73, 76, 58, 32, 67, 104, 97, 114, 97, 99, 116, 101, 114, 32, 79, 102, 102, 115, 101, 116, 32, 65, 99, 99, 101, 115, 115, 32, 69, 114, 114, 111, 114, 0
str_lit_20: db 45, 45, 45, 32, 84, 101, 115, 116, 32, 51, 58, 32, 78, 101, 115, 116, 101, 100, 32, 87, 111, 114, 100, 32, 38, 32, 76, 101, 116, 116, 101, 114, 32, 76, 111, 111, 112, 32, 40, 86, 111, 119, 101, 108, 32, 67, 111, 117, 110, 116, 101, 114, 41, 32, 45, 45, 45, 0
str_lit_21: db 86, 111, 119, 101, 108, 32, 99, 111, 117, 110, 116, 32, 105, 110, 32, 39, 109, 97, 99, 104, 105, 110, 101, 39, 32, 40, 69, 120, 112, 101, 99, 116, 101, 100, 32, 51, 41, 58, 0
str_lit_22: db 62, 62, 32, 80, 65, 83, 83, 58, 32, 78, 101, 115, 116, 101, 100, 32, 67, 104, 97, 114, 97, 99, 116, 101, 114, 32, 76, 111, 111, 112, 32, 38, 32, 80, 114, 101, 100, 105, 99, 97, 116, 101, 32, 86, 101, 114, 105, 102, 105, 101, 100, 0
str_lit_23: db 62, 62, 32, 70, 65, 73, 76, 58, 32, 67, 104, 97, 114, 97, 99, 116, 101, 114, 32, 76, 111, 111, 112, 32, 86, 111, 119, 101, 108, 32, 67, 111, 117, 110, 116, 32, 73, 110, 99, 111, 114, 114, 101, 99, 116, 0
str_lit_24: db 45, 45, 45, 32, 84, 101, 115, 116, 32, 52, 58, 32, 75, 101, 121, 119, 111, 114, 100, 32, 76, 111, 111, 107, 117, 112, 32, 105, 110, 32, 83, 116, 114, 105, 110, 103, 32, 65, 114, 114, 97, 121, 32, 45, 45, 45, 0
str_lit_25: db 115, 108, 111, 116, 0
str_lit_26: db 112, 114, 111, 99, 0
str_lit_27: db 100, 117, 114, 105, 110, 103, 0
str_lit_28: db 119, 104, 101, 110, 0
str_lit_29: db 121, 105, 101, 108, 100, 0
str_lit_30: db 76, 111, 111, 107, 117, 112, 32, 39, 100, 117, 114, 105, 110, 103, 39, 32, 40, 69, 120, 112, 101, 99, 116, 101, 100, 32, 105, 110, 100, 101, 120, 32, 50, 41, 58, 0
str_lit_31: db 76, 111, 111, 107, 117, 112, 32, 39, 121, 105, 101, 108, 100, 39, 32, 40, 69, 120, 112, 101, 99, 116, 101, 100, 32, 105, 110, 100, 101, 120, 32, 52, 41, 58, 0
str_lit_32: db 114, 101, 116, 117, 114, 110, 0
str_lit_33: db 76, 111, 111, 107, 117, 112, 32, 39, 114, 101, 116, 117, 114, 110, 39, 32, 40, 69, 120, 112, 101, 99, 116, 101, 100, 32, 105, 110, 100, 101, 120, 32, 45, 49, 41, 58, 0
str_lit_34: db 62, 62, 32, 80, 65, 83, 83, 58, 32, 67, 111, 109, 112, 105, 108, 101, 114, 32, 75, 101, 121, 119, 111, 114, 100, 32, 84, 97, 98, 108, 101, 32, 76, 111, 111, 107, 117, 112, 32, 86, 101, 114, 105, 102, 105, 101, 100, 0
str_lit_35: db 62, 62, 32, 70, 65, 73, 76, 58, 32, 75, 101, 121, 119, 111, 114, 100, 32, 84, 97, 98, 108, 101, 32, 83, 101, 97, 114, 99, 104, 32, 70, 97, 105, 108, 101, 100, 0
str_lit_36: db 45, 45, 45, 32, 84, 101, 115, 116, 32, 53, 58, 32, 82, 101, 118, 101, 114, 115, 101, 32, 83, 116, 114, 105, 110, 103, 32, 111, 110, 116, 111, 32, 72, 101, 97, 112, 32, 102, 114, 111, 109, 32, 65, 114, 114, 97, 121, 32, 45, 45, 45, 0
str_lit_37: db 79, 114, 105, 103, 105, 110, 97, 108, 32, 119, 111, 114, 100, 58, 0
str_lit_38: db 82, 101, 118, 101, 114, 115, 101, 100, 32, 119, 111, 114, 100, 32, 111, 110, 32, 104, 101, 97, 112, 32, 40, 69, 120, 112, 101, 99, 116, 101, 100, 32, 39, 121, 108, 98, 109, 101, 115, 115, 97, 39, 41, 58, 0
str_lit_39: db 62, 62, 32, 80, 65, 83, 83, 58, 32, 72, 101, 97, 112, 45, 82, 101, 118, 101, 114, 115, 101, 100, 32, 83, 116, 114, 105, 110, 103, 32, 65, 108, 108, 111, 99, 97, 116, 101, 100, 32, 38, 32, 80, 117, 114, 103, 101, 100, 32, 67, 108, 101, 97, 110, 108, 121, 0
str_lit_40: db 61, 61, 61, 32, 83, 116, 114, 101, 115, 115, 32, 84, 101, 115, 116, 32, 52, 32, 67, 111, 109, 112, 108, 101, 116, 101, 58, 32, 49, 48, 48, 37, 32, 80, 97, 115, 115, 101, 100, 32, 61, 61, 61, 0

section .bss
reg_83: resq 1
reg_84: resq 1
reg_85: resq 1
reg_86: resq 1
reg_87: resq 1
reg_88: resq 1
reg_89: resq 1
reg_90: resq 1
reg_91: resq 1
reg_92: resq 1
reg_93: resq 1
reg_94: resq 1
reg_95: resq 1
reg_96: resq 1
reg_97: resq 1
reg_98: resq 1
reg_99: resq 1
reg_100: resq 1
reg_101: resq 1
reg_102: resq 1
reg_103: resq 1
reg_104: resq 1
reg_105: resq 1
reg_106: resq 1
reg_107: resq 1
reg_108: resq 1
reg_109: resq 1
reg_110: resq 1
reg_111: resq 1
reg_112: resq 1
reg_113: resq 1
reg_114: resq 1
reg_115: resq 1
reg_116: resq 1
reg_117: resq 1
reg_118: resq 1
reg_119: resq 1
reg_120: resq 1
reg_121: resq 1
reg_122: resq 1
reg_123: resq 1
reg_124: resq 1
reg_125: resq 1
reg_126: resq 1
reg_127: resq 1
reg_128: resq 1
reg_129: resq 1
reg_130: resq 1
reg_131: resq 1
reg_132: resq 1
reg_133: resq 1
reg_134: resq 1
reg_135: resq 1
reg_136: resq 1
reg_137: resq 1
reg_138: resq 1
reg_139: resq 1
reg_140: resq 1
reg_141: resq 1
reg_142: resq 1
reg_143: resq 1
reg_144: resq 1
reg_145: resq 1
reg_146: resq 1
reg_147: resq 1
reg_148: resq 1
reg_149: resq 1
reg_150: resq 1
reg_151: resq 1
reg_152: resq 1
reg_153: resq 1
reg_154: resq 1
reg_155: resq 1
reg_156: resq 1
reg_157: resq 1
reg_158: resq 1
reg_159: resq 1
reg_160: resq 1
reg_161: resq 1
reg_162: resq 1
reg_163: resq 1
reg_164: resq 1
reg_165: resq 1
reg_166: resq 1
reg_167: resq 1
reg_168: resq 1
reg_169: resq 1
reg_170: resq 1
reg_171: resq 1
reg_172: resq 1
reg_173: resq 1
reg_174: resq 1
reg_175: resq 1
reg_176: resq 1
reg_177: resq 1
reg_178: resq 1
reg_179: resq 1
reg_180: resq 1
reg_181: resq 1
reg_182: resq 1
reg_183: resq 1
reg_184: resq 1
reg_185: resq 1
reg_186: resq 1
reg_187: resq 1
reg_188: resq 1
reg_189: resq 1
reg_190: resq 1
reg_191: resq 1
reg_192: resq 1
reg_193: resq 1
reg_194: resq 1
reg_195: resq 1
reg_196: resq 1
reg_197: resq 1
reg_198: resq 1
reg_199: resq 1
reg_200: resq 1
reg_201: resq 1
reg_202: resq 1
reg_203: resq 1
reg_204: resq 1
reg_205: resq 1
reg_206: resq 1
reg_207: resq 1
reg_208: resq 1
reg_209: resq 1
reg_210: resq 1
reg_211: resq 1
reg_212: resq 1
reg_213: resq 1
reg_214: resq 1
reg_215: resq 1
reg_216: resq 1
reg_217: resq 1
reg_218: resq 1
reg_219: resq 1
reg_220: resq 1
reg_221: resq 1
reg_222: resq 1
reg_223: resq 1
reg_224: resq 1
reg_225: resq 1
reg_226: resq 1
reg_227: resq 1
reg_228: resq 1
reg_229: resq 1
reg_230: resq 1
reg_231: resq 1
reg_232: resq 1
reg_233: resq 1
reg_234: resq 1
reg_235: resq 1
reg_236: resq 1
reg_237: resq 1
reg_238: resq 1
reg_239: resq 1
reg_240: resq 1
reg_241: resq 1
reg_242: resq 1
reg_243: resq 1
reg_244: resq 1
reg_245: resq 1
reg_246: resq 1
reg_247: resq 1
reg_248: resq 1
reg_249: resq 1
reg_250: resq 1
reg_251: resq 1
reg_252: resq 1
reg_253: resq 1
reg_254: resq 1
reg_255: resq 1
reg_256: resq 1
reg_257: resq 1
reg_258: resq 1
reg_259: resq 1
reg_260: resq 1
reg_261: resq 1
reg_262: resq 1
reg_263: resq 1
reg_264: resq 1
reg_265: resq 1
reg_266: resq 1
reg_267: resq 1
reg_268: resq 1
reg_269: resq 1
reg_270: resq 1
reg_271: resq 1
reg_272: resq 1
reg_273: resq 1
reg_274: resq 1
reg_275: resq 1
reg_276: resq 1
reg_277: resq 1
reg_278: resq 1
reg_279: resq 1
reg_280: resq 1
reg_281: resq 1
reg_282: resq 1
reg_283: resq 1
reg_284: resq 1
reg_285: resq 1
reg_286: resq 1
reg_287: resq 1
reg_288: resq 1
reg_289: resq 1
reg_290: resq 1
reg_291: resq 1
reg_292: resq 1
reg_293: resq 1
reg_294: resq 1
reg_295: resq 1
reg_296: resq 1
reg_297: resq 1
reg_298: resq 1
reg_299: resq 1
reg_300: resq 1
reg_301: resq 1
reg_302: resq 1
reg_303: resq 1
reg_304: resq 1
reg_305: resq 1
reg_306: resq 1

var_byte_val: resq 8
var_c_first: resq 8
var_c_last: resq 8
var_c_second: resq 8
var_ch: resq 8
var_idx_during: resq 8
var_idx_return: resq 8
var_idx_yield: resq 8
var_keywords: resq 8
var_len0: resq 8
var_len1: resq 8
var_letter_idx: resq 8
var_read_idx: resq 8
var_rev_i: resq 8
var_reversed_heap: resq 8
var_src_len: resq 8
var_src_word: resq 8
var_target_word: resq 8
var_vowel_count: resq 8
var_w_len: resq 8
var_words: resq 8

bytes_written: resd 1

section .text
global mainCRTStartup

string_length:
    push rbp
    mov rbp, rsp
    sub rsp, 176
    mov [rbp - 8], rcx
    mov rax, 0
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    mov [rbp - 16], rax
    mov rax, [rbp - 8]
    mov [rbp - 40], rax
    mov rax, [rbp - 40]
    mov [rbp - 24], rax
during_start_0:
    mov rax, [rbp - 24]
    mov [rbp - 48], rax
    mov rax, [rbp - 16]
    mov [rbp - 56], rax
    mov rax, [rbp - 48]
    add rax, [rbp - 56]
    mov [rbp - 64], rax
    mov rax, [rbp - 64]
    mov rbx, [rax]
    mov [rbp - 72], rbx
    mov rax, 256
    mov [rbp - 80], rax
    mov rax, [rbp - 72]
    cqo
    mov rbx, [rbp - 80]
    idiv rbx
    mov [rbp - 88], rdx
    mov rax, 0
    mov [rbp - 96], rax
    mov rax, [rbp - 88]
    cmp rax, [rbp - 96]
    setne al
    movzx rax, al
    mov [rbp - 104], rax
    mov rax, [rbp - 104]
    test rax, rax
    jz during_end_1
    mov rax, [rbp - 16]
    mov [rbp - 112], rax
    mov rax, 1
    mov [rbp - 120], rax
    mov rax, [rbp - 112]
    add rax, [rbp - 120]
    mov [rbp - 128], rax
    mov rax, [rbp - 128]
    mov [rbp - 16], rax
    jmp during_start_0
during_end_1:
    mov rax, [rbp - 16]
    mov [rbp - 136], rax
    mov rax, [rbp - 136]
    mov rsp, rbp
    pop rbp
    ret
    mov rsp, rbp
    pop rbp
    ret

char_at:
    push rbp
    mov rbp, rsp
    sub rsp, 128
    mov [rbp - 8], rcx
    mov [rbp - 16], rdx
    mov rax, [rbp - 8]
    mov [rbp - 32], rax
    mov rax, [rbp - 32]
    mov [rbp - 24], rax
    mov rax, [rbp - 24]
    mov [rbp - 40], rax
    mov rax, [rbp - 16]
    mov [rbp - 48], rax
    mov rax, [rbp - 40]
    add rax, [rbp - 48]
    mov [rbp - 56], rax
    mov rax, [rbp - 56]
    mov rbx, [rax]
    mov [rbp - 64], rbx
    mov rax, 256
    mov [rbp - 72], rax
    mov rax, [rbp - 64]
    cqo
    mov rbx, [rbp - 72]
    idiv rbx
    mov [rbp - 80], rdx
    mov rax, [rbp - 80]
    mov rsp, rbp
    pop rbp
    ret
    mov rsp, rbp
    pop rbp
    ret

is_vowel:
    push rbp
    mov rbp, rsp
    sub rsp, 224
    mov [rbp - 8], rcx
    mov rax, [rbp - 8]
    mov [rbp - 16], rax
    mov rax, 97
    mov [rbp - 24], rax
    mov rax, [rbp - 16]
    cmp rax, [rbp - 24]
    sete al
    movzx rax, al
    mov [rbp - 32], rax
    mov rax, [rbp - 8]
    mov [rbp - 40], rax
    mov rax, 101
    mov [rbp - 48], rax
    mov rax, [rbp - 40]
    cmp rax, [rbp - 48]
    sete al
    movzx rax, al
    mov [rbp - 56], rax
    mov rax, [rbp - 32]
    or rax, [rbp - 56]
    mov [rbp - 64], rax
    mov rax, [rbp - 8]
    mov [rbp - 72], rax
    mov rax, 105
    mov [rbp - 80], rax
    mov rax, [rbp - 72]
    cmp rax, [rbp - 80]
    sete al
    movzx rax, al
    mov [rbp - 88], rax
    mov rax, [rbp - 64]
    or rax, [rbp - 88]
    mov [rbp - 96], rax
    mov rax, [rbp - 8]
    mov [rbp - 104], rax
    mov rax, 111
    mov [rbp - 112], rax
    mov rax, [rbp - 104]
    cmp rax, [rbp - 112]
    sete al
    movzx rax, al
    mov [rbp - 120], rax
    mov rax, [rbp - 96]
    or rax, [rbp - 120]
    mov [rbp - 128], rax
    mov rax, [rbp - 8]
    mov [rbp - 136], rax
    mov rax, 117
    mov [rbp - 144], rax
    mov rax, [rbp - 136]
    cmp rax, [rbp - 144]
    sete al
    movzx rax, al
    mov [rbp - 152], rax
    mov rax, [rbp - 128]
    or rax, [rbp - 152]
    mov [rbp - 160], rax
    mov rax, [rbp - 160]
    test rax, rax
    jz else_2
    mov rax, 1
    mov [rbp - 168], rax
    mov rax, [rbp - 168]
    mov rsp, rbp
    pop rbp
    ret
else_2:
    mov rax, 0
    mov [rbp - 176], rax
    mov rax, [rbp - 176]
    mov rsp, rbp
    pop rbp
    ret
    mov rsp, rbp
    pop rbp
    ret

lookup_keyword:
    push rbp
    mov rbp, rsp
    sub rsp, 448
    mov [rbp - 8], rcx
    mov [rbp - 16], rdx
    mov [rbp - 24], r8
    mov rax, [rbp - 24]
    mov [rbp - 80], rax
    mov rcx, [rbp - 80]
    sub rsp, 32
    call string_length
    add rsp, 32
    mov [rbp - 88], rax
    mov rax, [rbp - 88]
    mov [rbp - 72], rax
    mov rax, 0
    mov [rbp - 96], rax
    mov rax, [rbp - 96]
    mov [rbp - 56], rax
during_start_4:
    mov rax, [rbp - 56]
    mov [rbp - 104], rax
    mov rax, [rbp - 16]
    mov [rbp - 112], rax
    mov rax, [rbp - 104]
    cmp rax, [rbp - 112]
    setl al
    movzx rax, al
    mov [rbp - 120], rax
    mov rax, [rbp - 120]
    test rax, rax
    jz during_end_5
    mov rax, [rbp - 8]
    mov [rbp - 128], rax
    mov rax, [rbp - 56]
    mov [rbp - 136], rax
    mov rax, 8
    mov [rbp - 144], rax
    mov rax, [rbp - 136]
    imul rax, [rbp - 144]
    mov [rbp - 152], rax
    mov rax, [rbp - 128]
    add rax, [rbp - 152]
    mov [rbp - 160], rax
    mov rax, [rbp - 160]
    mov rbx, [rax]
    mov [rbp - 168], rbx
    mov rax, [rbp - 168]
    mov [rbp - 48], rax
    mov rax, [rbp - 48]
    mov [rbp - 176], rax
    mov rcx, [rbp - 176]
    sub rsp, 32
    call string_length
    add rsp, 32
    mov [rbp - 184], rax
    mov rax, [rbp - 184]
    mov [rbp - 40], rax
    mov rax, [rbp - 72]
    mov [rbp - 192], rax
    mov rax, [rbp - 40]
    mov [rbp - 200], rax
    mov rax, [rbp - 192]
    cmp rax, [rbp - 200]
    sete al
    movzx rax, al
    mov [rbp - 208], rax
    mov rax, [rbp - 208]
    test rax, rax
    jz else_6
    mov rax, 1
    mov [rbp - 216], rax
    mov rax, [rbp - 216]
    mov [rbp - 64], rax
    mov rax, 0
    mov [rbp - 224], rax
    mov rax, [rbp - 224]
    mov [rbp - 32], rax
during_start_8:
    mov rax, [rbp - 32]
    mov [rbp - 232], rax
    mov rax, [rbp - 72]
    mov [rbp - 240], rax
    mov rax, [rbp - 232]
    cmp rax, [rbp - 240]
    setl al
    movzx rax, al
    mov [rbp - 248], rax
    mov rax, [rbp - 248]
    test rax, rax
    jz during_end_9
    mov rax, [rbp - 48]
    mov [rbp - 256], rax
    mov rax, [rbp - 32]
    mov [rbp - 264], rax
    mov rcx, [rbp - 256]
    mov rdx, [rbp - 264]
    sub rsp, 32
    call char_at
    add rsp, 32
    mov [rbp - 272], rax
    mov rax, [rbp - 24]
    mov [rbp - 280], rax
    mov rax, [rbp - 32]
    mov [rbp - 288], rax
    mov rcx, [rbp - 280]
    mov rdx, [rbp - 288]
    sub rsp, 32
    call char_at
    add rsp, 32
    mov [rbp - 296], rax
    mov rax, [rbp - 272]
    cmp rax, [rbp - 296]
    setne al
    movzx rax, al
    mov [rbp - 304], rax
    mov rax, [rbp - 304]
    test rax, rax
    jz else_10
    mov rax, 0
    mov [rbp - 312], rax
    mov rax, [rbp - 312]
    mov [rbp - 64], rax
else_10:
    mov rax, [rbp - 32]
    mov [rbp - 320], rax
    mov rax, 1
    mov [rbp - 328], rax
    mov rax, [rbp - 320]
    add rax, [rbp - 328]
    mov [rbp - 336], rax
    mov rax, [rbp - 336]
    mov [rbp - 32], rax
    jmp during_start_8
during_end_9:
    mov rax, [rbp - 64]
    mov [rbp - 344], rax
    mov rax, [rbp - 344]
    test rax, rax
    jz else_12
    mov rax, [rbp - 56]
    mov [rbp - 352], rax
    mov rax, [rbp - 352]
    mov rsp, rbp
    pop rbp
    ret
else_12:
else_6:
    mov rax, [rbp - 56]
    mov [rbp - 360], rax
    mov rax, 1
    mov [rbp - 368], rax
    mov rax, [rbp - 360]
    add rax, [rbp - 368]
    mov [rbp - 376], rax
    mov rax, [rbp - 376]
    mov [rbp - 56], rax
    jmp during_start_4
during_end_5:
    mov rax, 1
    mov [rbp - 384], rax
    mov rax, 0
    mov [rbp - 400], rax
    mov rax, [rbp - 400]
    sub rax, [rbp - 384]
    mov [rbp - 392], rax
    mov rax, [rbp - 392]
    mov rsp, rbp
    pop rbp
    ret
    mov rsp, rbp
    pop rbp
    ret

mainCRTStartup:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    lea rax, [str_lit_0]
    mov [reg_83], rax
    mov rcx, [reg_83]
    call print_string
    lea rax, [str_lit_1]
    mov [reg_84], rax
    mov rcx, [reg_84]
    call print_string
    lea rax, [str_lit_2]
    mov [reg_85], rax
    lea rax, [var_words]
    mov [reg_86], rax
    mov rax, 0
    mov [reg_87], rax
    mov rax, [reg_86]
    mov rbx, [reg_87]
    imul rbx, 8
    add rax, rbx
    mov [reg_88], rax
    mov rax, [reg_88]
    mov rbx, [reg_85]
    mov [rax], rbx
    lea rax, [str_lit_3]
    mov [reg_89], rax
    lea rax, [var_words]
    mov [reg_90], rax
    mov rax, 1
    mov [reg_91], rax
    mov rax, [reg_90]
    mov rbx, [reg_91]
    imul rbx, 8
    add rax, rbx
    mov [reg_92], rax
    mov rax, [reg_92]
    mov rbx, [reg_89]
    mov [rax], rbx
    lea rax, [str_lit_4]
    mov [reg_93], rax
    lea rax, [var_words]
    mov [reg_94], rax
    mov rax, 2
    mov [reg_95], rax
    mov rax, [reg_94]
    mov rbx, [reg_95]
    imul rbx, 8
    add rax, rbx
    mov [reg_96], rax
    mov rax, [reg_96]
    mov rbx, [reg_93]
    mov [rax], rbx
    lea rax, [str_lit_5]
    mov [reg_97], rax
    lea rax, [var_words]
    mov [reg_98], rax
    mov rax, 3
    mov [reg_99], rax
    mov rax, [reg_98]
    mov rbx, [reg_99]
    imul rbx, 8
    add rax, rbx
    mov [reg_100], rax
    mov rax, [reg_100]
    mov rbx, [reg_97]
    mov [rax], rbx
    lea rax, [str_lit_6]
    mov [reg_101], rax
    mov rcx, [reg_101]
    call print_string
    lea rax, [var_words]
    mov [reg_102], rax
    mov rax, 0
    mov [reg_103], rax
    mov rax, [reg_102]
    mov rbx, [reg_103]
    imul rbx, 8
    add rax, rbx
    mov [reg_104], rax
    mov rax, [reg_104]
    mov rbx, [rax]
    mov [reg_105], rbx
    mov rcx, [reg_105]
    call print_string
    lea rax, [str_lit_7]
    mov [reg_106], rax
    mov rcx, [reg_106]
    call print_string
    lea rax, [var_words]
    mov [reg_107], rax
    mov rax, 1
    mov [reg_108], rax
    mov rax, [reg_107]
    mov rbx, [reg_108]
    imul rbx, 8
    add rax, rbx
    mov [reg_109], rax
    mov rax, [reg_109]
    mov rbx, [rax]
    mov [reg_110], rbx
    mov rcx, [reg_110]
    call print_string
    lea rax, [str_lit_8]
    mov [reg_111], rax
    mov rcx, [reg_111]
    call print_string
    lea rax, [var_words]
    mov [reg_112], rax
    mov rax, 2
    mov [reg_113], rax
    mov rax, [reg_112]
    mov rbx, [reg_113]
    imul rbx, 8
    add rax, rbx
    mov [reg_114], rax
    mov rax, [reg_114]
    mov rbx, [rax]
    mov [reg_115], rbx
    mov rcx, [reg_115]
    call print_string
    lea rax, [str_lit_9]
    mov [reg_116], rax
    mov rcx, [reg_116]
    call print_string
    lea rax, [var_words]
    mov [reg_117], rax
    mov rax, 3
    mov [reg_118], rax
    mov rax, [reg_117]
    mov rbx, [reg_118]
    imul rbx, 8
    add rax, rbx
    mov [reg_119], rax
    mov rax, [reg_119]
    mov rbx, [rax]
    mov [reg_120], rbx
    mov rcx, [reg_120]
    call print_string
    lea rax, [var_words]
    mov [reg_121], rax
    mov rax, 0
    mov [reg_122], rax
    mov rax, [reg_121]
    mov rbx, [reg_122]
    imul rbx, 8
    add rax, rbx
    mov [reg_123], rax
    mov rax, [reg_123]
    mov rbx, [rax]
    mov [reg_124], rbx
    mov rcx, [reg_124]
    sub rsp, 32
    call string_length
    add rsp, 32
    mov [reg_125], rax
    mov rax, [reg_125]
    mov [var_len0], rax
    lea rax, [var_words]
    mov [reg_126], rax
    mov rax, 1
    mov [reg_127], rax
    mov rax, [reg_126]
    mov rbx, [reg_127]
    imul rbx, 8
    add rax, rbx
    mov [reg_128], rax
    mov rax, [reg_128]
    mov rbx, [rax]
    mov [reg_129], rbx
    mov rcx, [reg_129]
    sub rsp, 32
    call string_length
    add rsp, 32
    mov [reg_130], rax
    mov rax, [reg_130]
    mov [var_len1], rax
    lea rax, [str_lit_10]
    mov [reg_131], rax
    mov rcx, [reg_131]
    call print_string
    mov rax, [var_len0]
    mov [reg_132], rax
    mov rcx, [reg_132]
    call print_int
    lea rax, [str_lit_11]
    mov [reg_133], rax
    mov rcx, [reg_133]
    call print_string
    mov rax, [var_len1]
    mov [reg_134], rax
    mov rcx, [reg_134]
    call print_int
    mov rax, [var_len0]
    mov [reg_135], rax
    mov rax, 8
    mov [reg_136], rax
    mov rax, [reg_135]
    cmp rax, [reg_136]
    sete al
    movzx rax, al
    mov [reg_137], rax
    mov rax, [var_len1]
    mov [reg_138], rax
    mov rax, 12
    mov [reg_139], rax
    mov rax, [reg_138]
    cmp rax, [reg_139]
    sete al
    movzx rax, al
    mov [reg_140], rax
    mov rax, [reg_137]
    and rax, [reg_140]
    mov [reg_141], rax
    mov rax, [reg_141]
    test rax, rax
    jz else_14
    lea rax, [str_lit_12]
    mov [reg_142], rax
    mov rcx, [reg_142]
    call print_string
    jmp end_when_15
else_14:
    lea rax, [str_lit_13]
    mov [reg_143], rax
    mov rcx, [reg_143]
    call print_string
end_when_15:
    lea rax, [str_lit_14]
    mov [reg_144], rax
    mov rcx, [reg_144]
    call print_string
    lea rax, [var_words]
    mov [reg_145], rax
    mov rax, 0
    mov [reg_146], rax
    mov rax, [reg_145]
    mov rbx, [reg_146]
    imul rbx, 8
    add rax, rbx
    mov [reg_147], rax
    mov rax, [reg_147]
    mov rbx, [rax]
    mov [reg_148], rbx
    mov rax, 0
    mov [reg_149], rax
    mov rcx, [reg_148]
    mov rdx, [reg_149]
    sub rsp, 32
    call char_at
    add rsp, 32
    mov [reg_150], rax
    mov rax, [reg_150]
    mov [var_c_first], rax
    lea rax, [var_words]
    mov [reg_151], rax
    mov rax, 0
    mov [reg_152], rax
    mov rax, [reg_151]
    mov rbx, [reg_152]
    imul rbx, 8
    add rax, rbx
    mov [reg_153], rax
    mov rax, [reg_153]
    mov rbx, [rax]
    mov [reg_154], rbx
    mov rax, 1
    mov [reg_155], rax
    mov rcx, [reg_154]
    mov rdx, [reg_155]
    sub rsp, 32
    call char_at
    add rsp, 32
    mov [reg_156], rax
    mov rax, [reg_156]
    mov [var_c_second], rax
    lea rax, [var_words]
    mov [reg_157], rax
    mov rax, 0
    mov [reg_158], rax
    mov rax, [reg_157]
    mov rbx, [reg_158]
    imul rbx, 8
    add rax, rbx
    mov [reg_159], rax
    mov rax, [reg_159]
    mov rbx, [rax]
    mov [reg_160], rbx
    mov rax, 7
    mov [reg_161], rax
    mov rcx, [reg_160]
    mov rdx, [reg_161]
    sub rsp, 32
    call char_at
    add rsp, 32
    mov [reg_162], rax
    mov rax, [reg_162]
    mov [var_c_last], rax
    lea rax, [str_lit_15]
    mov [reg_163], rax
    mov rcx, [reg_163]
    call print_string
    mov rax, [var_c_first]
    mov [reg_164], rax
    mov rcx, [reg_164]
    call print_int
    lea rax, [str_lit_16]
    mov [reg_165], rax
    mov rcx, [reg_165]
    call print_string
    mov rax, [var_c_second]
    mov [reg_166], rax
    mov rcx, [reg_166]
    call print_int
    lea rax, [str_lit_17]
    mov [reg_167], rax
    mov rcx, [reg_167]
    call print_string
    mov rax, [var_c_last]
    mov [reg_168], rax
    mov rcx, [reg_168]
    call print_int
    mov rax, [var_c_first]
    mov [reg_169], rax
    mov rax, 99
    mov [reg_170], rax
    mov rax, [reg_169]
    cmp rax, [reg_170]
    sete al
    movzx rax, al
    mov [reg_171], rax
    mov rax, [var_c_second]
    mov [reg_172], rax
    mov rax, 111
    mov [reg_173], rax
    mov rax, [reg_172]
    cmp rax, [reg_173]
    sete al
    movzx rax, al
    mov [reg_174], rax
    mov rax, [reg_171]
    and rax, [reg_174]
    mov [reg_175], rax
    mov rax, [var_c_last]
    mov [reg_176], rax
    mov rax, 114
    mov [reg_177], rax
    mov rax, [reg_176]
    cmp rax, [reg_177]
    sete al
    movzx rax, al
    mov [reg_178], rax
    mov rax, [reg_175]
    and rax, [reg_178]
    mov [reg_179], rax
    mov rax, [reg_179]
    test rax, rax
    jz else_16
    lea rax, [str_lit_18]
    mov [reg_180], rax
    mov rcx, [reg_180]
    call print_string
    jmp end_when_17
else_16:
    lea rax, [str_lit_19]
    mov [reg_181], rax
    mov rcx, [reg_181]
    call print_string
end_when_17:
    lea rax, [str_lit_20]
    mov [reg_182], rax
    mov rcx, [reg_182]
    call print_string
    mov rax, 0
    mov [reg_183], rax
    mov rax, [reg_183]
    mov [var_vowel_count], rax
    lea rax, [var_words]
    mov [reg_184], rax
    mov rax, 3
    mov [reg_185], rax
    mov rax, [reg_184]
    mov rbx, [reg_185]
    imul rbx, 8
    add rax, rbx
    mov [reg_186], rax
    mov rax, [reg_186]
    mov rbx, [rax]
    mov [reg_187], rbx
    mov rax, [reg_187]
    mov [var_target_word], rax
    mov rax, [var_target_word]
    mov [reg_188], rax
    mov rcx, [reg_188]
    sub rsp, 32
    call string_length
    add rsp, 32
    mov [reg_189], rax
    mov rax, [reg_189]
    mov [var_w_len], rax
    mov rax, 0
    mov [reg_190], rax
    mov rax, [reg_190]
    mov [var_letter_idx], rax
during_start_18:
    mov rax, [var_letter_idx]
    mov [reg_191], rax
    mov rax, [var_w_len]
    mov [reg_192], rax
    mov rax, [reg_191]
    cmp rax, [reg_192]
    setl al
    movzx rax, al
    mov [reg_193], rax
    mov rax, [reg_193]
    test rax, rax
    jz during_end_19
    mov rax, [var_target_word]
    mov [reg_194], rax
    mov rax, [var_letter_idx]
    mov [reg_195], rax
    mov rcx, [reg_194]
    mov rdx, [reg_195]
    sub rsp, 32
    call char_at
    add rsp, 32
    mov [reg_196], rax
    mov rax, [reg_196]
    mov [var_ch], rax
    mov rax, [var_ch]
    mov [reg_197], rax
    mov rcx, [reg_197]
    sub rsp, 32
    call is_vowel
    add rsp, 32
    mov [reg_198], rax
    mov rax, [reg_198]
    test rax, rax
    jz else_20
    mov rax, [var_vowel_count]
    mov [reg_199], rax
    mov rax, 1
    mov [reg_200], rax
    mov rax, [reg_199]
    add rax, [reg_200]
    mov [reg_201], rax
    mov rax, [reg_201]
    mov [var_vowel_count], rax
else_20:
    mov rax, [var_letter_idx]
    mov [reg_202], rax
    mov rax, 1
    mov [reg_203], rax
    mov rax, [reg_202]
    add rax, [reg_203]
    mov [reg_204], rax
    mov rax, [reg_204]
    mov [var_letter_idx], rax
    jmp during_start_18
during_end_19:
    lea rax, [str_lit_21]
    mov [reg_205], rax
    mov rcx, [reg_205]
    call print_string
    mov rax, [var_vowel_count]
    mov [reg_206], rax
    mov rcx, [reg_206]
    call print_int
    mov rax, [var_vowel_count]
    mov [reg_207], rax
    mov rax, 3
    mov [reg_208], rax
    mov rax, [reg_207]
    cmp rax, [reg_208]
    sete al
    movzx rax, al
    mov [reg_209], rax
    mov rax, [reg_209]
    test rax, rax
    jz else_22
    lea rax, [str_lit_22]
    mov [reg_210], rax
    mov rcx, [reg_210]
    call print_string
    jmp end_when_23
else_22:
    lea rax, [str_lit_23]
    mov [reg_211], rax
    mov rcx, [reg_211]
    call print_string
end_when_23:
    lea rax, [str_lit_24]
    mov [reg_212], rax
    mov rcx, [reg_212]
    call print_string
    lea rax, [str_lit_25]
    mov [reg_213], rax
    lea rax, [var_keywords]
    mov [reg_214], rax
    mov rax, 0
    mov [reg_215], rax
    mov rax, [reg_214]
    mov rbx, [reg_215]
    imul rbx, 8
    add rax, rbx
    mov [reg_216], rax
    mov rax, [reg_216]
    mov rbx, [reg_213]
    mov [rax], rbx
    lea rax, [str_lit_26]
    mov [reg_217], rax
    lea rax, [var_keywords]
    mov [reg_218], rax
    mov rax, 1
    mov [reg_219], rax
    mov rax, [reg_218]
    mov rbx, [reg_219]
    imul rbx, 8
    add rax, rbx
    mov [reg_220], rax
    mov rax, [reg_220]
    mov rbx, [reg_217]
    mov [rax], rbx
    lea rax, [str_lit_27]
    mov [reg_221], rax
    lea rax, [var_keywords]
    mov [reg_222], rax
    mov rax, 2
    mov [reg_223], rax
    mov rax, [reg_222]
    mov rbx, [reg_223]
    imul rbx, 8
    add rax, rbx
    mov [reg_224], rax
    mov rax, [reg_224]
    mov rbx, [reg_221]
    mov [rax], rbx
    lea rax, [str_lit_28]
    mov [reg_225], rax
    lea rax, [var_keywords]
    mov [reg_226], rax
    mov rax, 3
    mov [reg_227], rax
    mov rax, [reg_226]
    mov rbx, [reg_227]
    imul rbx, 8
    add rax, rbx
    mov [reg_228], rax
    mov rax, [reg_228]
    mov rbx, [reg_225]
    mov [rax], rbx
    lea rax, [str_lit_29]
    mov [reg_229], rax
    lea rax, [var_keywords]
    mov [reg_230], rax
    mov rax, 4
    mov [reg_231], rax
    mov rax, [reg_230]
    mov rbx, [reg_231]
    imul rbx, 8
    add rax, rbx
    mov [reg_232], rax
    mov rax, [reg_232]
    mov rbx, [reg_229]
    mov [rax], rbx
    lea rax, [var_keywords]
    mov [reg_233], rax
    mov rax, 5
    mov [reg_234], rax
    lea rax, [str_lit_27]
    mov [reg_235], rax
    mov rcx, [reg_233]
    mov rdx, [reg_234]
    mov r8, [reg_235]
    sub rsp, 32
    call lookup_keyword
    add rsp, 32
    mov [reg_236], rax
    mov rax, [reg_236]
    mov [var_idx_during], rax
    lea rax, [str_lit_30]
    mov [reg_237], rax
    mov rcx, [reg_237]
    call print_string
    mov rax, [var_idx_during]
    mov [reg_238], rax
    mov rcx, [reg_238]
    call print_int
    lea rax, [var_keywords]
    mov [reg_239], rax
    mov rax, 5
    mov [reg_240], rax
    lea rax, [str_lit_29]
    mov [reg_241], rax
    mov rcx, [reg_239]
    mov rdx, [reg_240]
    mov r8, [reg_241]
    sub rsp, 32
    call lookup_keyword
    add rsp, 32
    mov [reg_242], rax
    mov rax, [reg_242]
    mov [var_idx_yield], rax
    lea rax, [str_lit_31]
    mov [reg_243], rax
    mov rcx, [reg_243]
    call print_string
    mov rax, [var_idx_yield]
    mov [reg_244], rax
    mov rcx, [reg_244]
    call print_int
    lea rax, [var_keywords]
    mov [reg_245], rax
    mov rax, 5
    mov [reg_246], rax
    lea rax, [str_lit_32]
    mov [reg_247], rax
    mov rcx, [reg_245]
    mov rdx, [reg_246]
    mov r8, [reg_247]
    sub rsp, 32
    call lookup_keyword
    add rsp, 32
    mov [reg_248], rax
    mov rax, [reg_248]
    mov [var_idx_return], rax
    lea rax, [str_lit_33]
    mov [reg_249], rax
    mov rcx, [reg_249]
    call print_string
    mov rax, [var_idx_return]
    mov [reg_250], rax
    mov rcx, [reg_250]
    call print_int
    mov rax, [var_idx_during]
    mov [reg_251], rax
    mov rax, 2
    mov [reg_252], rax
    mov rax, [reg_251]
    cmp rax, [reg_252]
    sete al
    movzx rax, al
    mov [reg_253], rax
    mov rax, [var_idx_yield]
    mov [reg_254], rax
    mov rax, 4
    mov [reg_255], rax
    mov rax, [reg_254]
    cmp rax, [reg_255]
    sete al
    movzx rax, al
    mov [reg_256], rax
    mov rax, [reg_253]
    and rax, [reg_256]
    mov [reg_257], rax
    mov rax, [var_idx_return]
    mov [reg_258], rax
    mov rax, 1
    mov [reg_259], rax
    mov rax, 0
    mov [reg_261], rax
    mov rax, [reg_261]
    sub rax, [reg_259]
    mov [reg_260], rax
    mov rax, [reg_258]
    cmp rax, [reg_260]
    sete al
    movzx rax, al
    mov [reg_262], rax
    mov rax, [reg_257]
    and rax, [reg_262]
    mov [reg_263], rax
    mov rax, [reg_263]
    test rax, rax
    jz else_24
    lea rax, [str_lit_34]
    mov [reg_264], rax
    mov rcx, [reg_264]
    call print_string
    jmp end_when_25
else_24:
    lea rax, [str_lit_35]
    mov [reg_265], rax
    mov rcx, [reg_265]
    call print_string
end_when_25:
    lea rax, [str_lit_36]
    mov [reg_266], rax
    mov rcx, [reg_266]
    call print_string
    lea rax, [var_words]
    mov [reg_267], rax
    mov rax, 2
    mov [reg_268], rax
    mov rax, [reg_267]
    mov rbx, [reg_268]
    imul rbx, 8
    add rax, rbx
    mov [reg_269], rax
    mov rax, [reg_269]
    mov rbx, [rax]
    mov [reg_270], rbx
    mov rax, [reg_270]
    mov [var_src_word], rax
    mov rax, [var_src_word]
    mov [reg_271], rax
    mov rcx, [reg_271]
    sub rsp, 32
    call string_length
    add rsp, 32
    mov [reg_272], rax
    mov rax, [reg_272]
    mov [var_src_len], rax
    mov rax, [var_src_len]
    mov [reg_273], rax
    mov rax, 8
    mov [reg_274], rax
    mov rax, [reg_273]
    add rax, [reg_274]
    mov [reg_275], rax
    ; claim(size) -> kernel32!HeapAlloc
    sub rsp, 40
    call GetProcessHeap
    mov rcx, rax
    mov rdx, 8
    mov r8, [reg_275]
    call HeapAlloc
    add rsp, 40
    mov [reg_276], rax
    mov rax, [reg_276]
    mov [var_reversed_heap], rax
    mov rax, 0
    mov [reg_277], rax
    mov rax, [reg_277]
    mov [var_rev_i], rax
during_start_26:
    mov rax, [var_rev_i]
    mov [reg_278], rax
    mov rax, [var_src_len]
    mov [reg_279], rax
    mov rax, [reg_278]
    cmp rax, [reg_279]
    setl al
    movzx rax, al
    mov [reg_280], rax
    mov rax, [reg_280]
    test rax, rax
    jz during_end_27
    mov rax, [var_src_len]
    mov [reg_281], rax
    mov rax, 1
    mov [reg_282], rax
    mov rax, [reg_281]
    sub rax, [reg_282]
    mov [reg_283], rax
    mov rax, [var_rev_i]
    mov [reg_284], rax
    mov rax, [reg_283]
    sub rax, [reg_284]
    mov [reg_285], rax
    mov rax, [reg_285]
    mov [var_read_idx], rax
    mov rax, [var_src_word]
    mov [reg_286], rax
    mov rax, [var_read_idx]
    mov [reg_287], rax
    mov rcx, [reg_286]
    mov rdx, [reg_287]
    sub rsp, 32
    call char_at
    add rsp, 32
    mov [reg_288], rax
    mov rax, [reg_288]
    mov [var_byte_val], rax
    mov rax, [var_byte_val]
    mov [reg_289], rax
    mov rax, [var_reversed_heap]
    mov [reg_290], rax
    mov rax, [var_rev_i]
    mov [reg_291], rax
    mov rax, [reg_290]
    add rax, [reg_291]
    mov [reg_292], rax
    mov rax, [reg_292]
    mov rbx, [reg_289]
    mov [rax], rbx
    mov rax, [var_rev_i]
    mov [reg_293], rax
    mov rax, 1
    mov [reg_294], rax
    mov rax, [reg_293]
    add rax, [reg_294]
    mov [reg_295], rax
    mov rax, [reg_295]
    mov [var_rev_i], rax
    jmp during_start_26
during_end_27:
    mov rax, 0
    mov [reg_296], rax
    mov rax, [var_reversed_heap]
    mov [reg_297], rax
    mov rax, [var_src_len]
    mov [reg_298], rax
    mov rax, [reg_297]
    add rax, [reg_298]
    mov [reg_299], rax
    mov rax, [reg_299]
    mov rbx, [reg_296]
    mov [rax], rbx
    lea rax, [str_lit_37]
    mov [reg_300], rax
    mov rcx, [reg_300]
    call print_string
    mov rax, [var_src_word]
    mov [reg_301], rax
    mov rcx, [reg_301]
    call print_string
    lea rax, [str_lit_38]
    mov [reg_302], rax
    mov rcx, [reg_302]
    call print_string
    mov rax, [var_reversed_heap]
    mov [reg_303], rax
    mov rcx, [reg_303]
    call print_string
    mov rax, [var_reversed_heap]
    mov [reg_304], rax
    ; purge(ptr) -> kernel32!HeapFree
    mov r8, [reg_304]
    sub rsp, 40
    call GetProcessHeap
    mov rcx, rax
    xor rdx, rdx
    call HeapFree
    add rsp, 40
    lea rax, [str_lit_39]
    mov [reg_305], rax
    mov rcx, [reg_305]
    call print_string
    lea rax, [str_lit_40]
    mov [reg_306], rax
    mov rcx, [reg_306]
    call print_string
    ; Terminate process via kernel32!ExitProcess(0)
    xor ecx, ecx
    call ExitProcess

; --- Freestanding Console I/O Runtime ---
print_crlf:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    mov ecx, -11       ; STD_OUTPUT_HANDLE
    call GetStdHandle
    mov rcx, rax
    lea rdx, [crlf]
    mov r8, 2
    lea r9, [bytes_written]
    mov qword [rsp + 32], 0
    call WriteFile
    add rsp, 48
    pop rbp
    ret

print_string:
    push rbp
    mov rbp, rsp
    push rbx
    push r12
    sub rsp, 48
    mov rbx, rcx
    xor r12, r12
.str_len_loop:
    cmp byte [rbx + r12], 0
    je .str_len_done
    inc r12
    jmp .str_len_loop
.str_len_done:
    mov ecx, -11       ; STD_OUTPUT_HANDLE
    call GetStdHandle
    mov rcx, rax
    mov rdx, rbx
    mov r8, r12
    lea r9, [bytes_written]
    mov qword [rsp + 32], 0
    call WriteFile
    call print_crlf
    add rsp, 48
    pop r12
    pop rbx
    pop rbp
    ret

print_bool:
    test rcx, rcx
    jz .print_b_false
    lea rcx, [str_true]
    jmp print_string
.print_b_false:
    lea rcx, [str_false]
    jmp print_string

print_int:
    push rbp
    mov rbp, rsp
    sub rsp, 64
    lea rdi, [rbp - 1]
    mov byte [rdi], 0
    mov rax, rcx
    xor r8d, r8d
    cmp rax, 0
    jge .p_pos
    neg rax
    mov r8b, 1
.p_pos:
    mov rbx, 10
.p_loop:
    xor rdx, rdx
    div rbx
    add dl, '0'
    dec rdi
    mov [rdi], dl
    test rax, rax
    jnz .p_loop
    test r8b, r8b
    jz .p_done
    dec rdi
    mov byte [rdi], '-'
.p_done:
    mov rcx, rdi
    call print_string
    add rsp, 64
    pop rbp
    ret

print_double:
    push rbp
    mov rbp, rsp
    sub rsp, 48
    cvttsd2si rax, xmm0
    mov rcx, rax
    call print_int
    add rsp, 48
    pop rbp
    ret

