use std::collections::{BTreeMap, BTreeSet};
use std::fs::File;
use std::io::{self, Write};
use crate::core::Type;
use crate::ir::{IRInstruction, IRProgram};

pub struct Emitter;

impl Emitter {
    pub fn new() -> Self {
        Emitter
    }

    pub fn emit_to_file(&self, program: &IRProgram, filename: &str) -> io::Result<()> {
        let mut file = File::create(filename)?;
        let (registers, global_vars) = self.collect_global_symbols(program);

        self.emit_preamble(&mut file)?;
        self.emit_data_section(&mut file, program)?;
        self.emit_bss_section(&mut file, &registers, &global_vars)?;
        self.emit_text_section(&mut file, program)?;

        Ok(())
    }

    fn emit_preamble(&self, file: &mut File) -> io::Result<()> {
        writeln!(file, "; ===================================================================")?;
        writeln!(file, "; Generated by Axiom Freestanding Windows x86-64 Compiler")?;
        writeln!(file, "; Zero CRT - Pure Kernel32.dll target (Reentrant Stack Frames)")?;
        writeln!(file, "; ===================================================================")?;
        writeln!(file, "default rel")?;
        writeln!(file)?;
        writeln!(file, "extern GetStdHandle")?;
        writeln!(file, "extern WriteFile")?;
        writeln!(file, "extern ExitProcess")?;
        writeln!(file, "extern GetProcessHeap")?;
        writeln!(file, "extern HeapAlloc")?;
        writeln!(file, "extern HeapFree")?;
        writeln!(file)?;
        Ok(())
    }

    fn emit_data_section(&self, file: &mut File, program: &IRProgram) -> io::Result<()> {
        writeln!(file, "section .data")?;
        writeln!(file, "const_1e6:  dq 1000000.0")?;
        writeln!(file, "const_half: dq 0.5")?;
        writeln!(file, "str_true:   db 'yes', 0")?;
        writeln!(file, "str_false:  db 'no', 0")?;
        writeln!(file, "crlf:       db 13, 10, 0")?;
        writeln!(file)?;

        for (id, s) in program.string_literals.iter().enumerate() {
            let mut bytes: Vec<u8> = s.bytes().collect();
            bytes.push(0); // Exact null-terminated string byte sequence
            let byte_strs: Vec<String> = bytes.iter().map(|b| b.to_string()).collect();
            writeln!(file, "str_lit_{}: db {}", id, byte_strs.join(", "))?;
        }
        writeln!(file)?;
        Ok(())
    }

    fn emit_bss_section(
        &self,
        file: &mut File,
        registers: &BTreeSet<usize>,
        global_vars: &BTreeSet<String>,
    ) -> io::Result<()> {
        writeln!(file, "section .bss")?;

        // 1. Top-level registers
        for reg in registers {
            writeln!(file, "reg_{}: resq 1", reg)?;
        }
        writeln!(file)?;

        // 2. Global variables (main script only)
        for var in global_vars {
            writeln!(file, "var_{}: resq 8", var)?;
        }
        writeln!(file)?;

        // 3. Freestanding I/O buffers
        writeln!(file, "bytes_written: resd 1")?;
        writeln!(file)?;
        Ok(())
    }

    fn emit_text_section(&self, file: &mut File, program: &IRProgram) -> io::Result<()> {
        writeln!(file, "section .text")?;
        writeln!(file, "global mainCRTStartup")?;
        writeln!(file)?;

        // 1. Emit procedures with true stack frames
        for p in &program.procs {
            self.emit_proc(file, p)?;
        }

        // 2. Main script entry
        writeln!(file, "mainCRTStartup:")?;
        writeln!(file, "    push rbp")?;
        writeln!(file, "    mov rbp, rsp")?;
        writeln!(file, "    sub rsp, 48")?;

        for ins in &program.main_instructions {
            self.emit_instruction(file, ins, None)?;
        }

        writeln!(file, "    ; Terminate process via kernel32!ExitProcess(0)")?;
        writeln!(file, "    xor ecx, ecx")?;
        writeln!(file, "    call ExitProcess")?;
        writeln!(file)?;

        // 3. Console output routines
        self.emit_runtime_formatters(file)?;

        Ok(())
    }

    fn emit_proc(&self, file: &mut File, proc: &crate::ir::IRProc) -> io::Result<()> {
        writeln!(file, "{}:", proc.name)?;
        writeln!(file, "    push rbp")?;
        writeln!(file, "    mov rbp, rsp")?;

        // Calculate stack slots for parameters, local variables, and registers
        let mut stack_map: BTreeMap<String, usize> = BTreeMap::new();
        let mut current_offset: usize = 8;

        for (p_name, _) in &proc.params {
            stack_map.insert(format!("var_{}", p_name), current_offset);
            current_offset += 8;
        }

        let (proc_regs, proc_vars) = self.collect_local_symbols(&proc.instructions);
        for v in proc_vars {
            let key = format!("var_{}", v);
            if !stack_map.contains_key(&key) {
                stack_map.insert(key, current_offset);
                current_offset += 8;
            }
        }
        for r in proc_regs {
            let key = format!("reg_{}", r);
            stack_map.insert(key, current_offset);
            current_offset += 8;
        }

        // 16-byte align the frame + 32 shadow space
        let total_frame = ((current_offset + 32 + 15) & !15).max(48);
        writeln!(file, "    sub rsp, {}", total_frame)?;

        // Store Win64 incoming register parameters into local stack slots
        let win64_int_regs = ["rcx", "rdx", "r8", "r9"];
        for (idx, (p_name, p_type)) in proc.params.iter().enumerate() {
            if idx < 4 {
                let offset = stack_map[&format!("var_{}", p_name)];
                if *p_type == Type::Num {
                    writeln!(file, "    movq [rbp - {}], xmm{}", offset, idx)?;
                } else {
                    writeln!(file, "    mov [rbp - {}], {}", offset, win64_int_regs[idx])?;
                }
            }
        }

        for ins in &proc.instructions {
            self.emit_instruction(file, ins, Some(&stack_map))?;
        }

        writeln!(file, "    mov rsp, rbp")?;
        writeln!(file, "    pop rbp")?;
        writeln!(file, "    ret")?;
        writeln!(file)?;
        Ok(())
    }

    fn mem_loc(name: &str, stack_map: Option<&BTreeMap<String, usize>>) -> String {
        if let Some(map) = stack_map {
            if let Some(offset) = map.get(name) {
                return format!("[rbp - {}]", offset);
            }
        }
        format!("[{}]", name)
    }

    fn emit_instruction(
        &self,
        file: &mut File,
        ins: &IRInstruction,
        stack_map: Option<&BTreeMap<String, usize>>,
    ) -> io::Result<()> {
        match ins {
            IRInstruction::LoadFloatConst { dest, val } => {
                let bits = val.to_bits();
                let loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, 0x{:x}", bits)?;
                writeln!(file, "    mov {}, rax", loc)?;
            }
            IRInstruction::LoadIntConst { dest, val } => {
                let loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", val)?;
                writeln!(file, "    mov {}, rax", loc)?;
            }
            IRInstruction::LoadStringConst { dest, str_id } => {
                let loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    lea rax, [str_lit_{}]", str_id)?;
                writeln!(file, "    mov {}, rax", loc)?;
            }
            IRInstruction::LoadBoolConst { dest, val } => {
                let loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", if *val { 1 } else { 0 })?;
                writeln!(file, "    mov {}, rax", loc)?;
            }
            IRInstruction::LoadVar { dest, name } => {
                let var_loc = Self::mem_loc(&format!("var_{}", name), stack_map);
                let reg_loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", var_loc)?;
                writeln!(file, "    mov {}, rax", reg_loc)?;
            }
            IRInstruction::StoreVar { name, src } => {
                let reg_loc = Self::mem_loc(&format!("reg_{}", src), stack_map);
                let var_loc = Self::mem_loc(&format!("var_{}", name), stack_map);
                writeln!(file, "    mov rax, {}", reg_loc)?;
                writeln!(file, "    mov {}, rax", var_loc)?;
            }
            IRInstruction::Add { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    addsd xmm0, xmm1")?;
                    writeln!(file, "    movq {}, xmm0", d)?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    add rax, {}", s2)?;
                    writeln!(file, "    mov {}, rax", d)?;
                }
            }
            IRInstruction::Sub { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    subsd xmm0, xmm1")?;
                    writeln!(file, "    movq {}, xmm0", d)?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    sub rax, {}", s2)?;
                    writeln!(file, "    mov {}, rax", d)?;
                }
            }
            IRInstruction::Mul { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    mulsd xmm0, xmm1")?;
                    writeln!(file, "    movq {}, xmm0", d)?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    imul rax, {}", s2)?;
                    writeln!(file, "    mov {}, rax", d)?;
                }
            }
            IRInstruction::Div { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    divsd xmm0, xmm1")?;
                    writeln!(file, "    movq {}, xmm0", d)?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cqo")?;
                    writeln!(file, "    mov rbx, {}", s2)?;
                    writeln!(file, "    idiv rbx")?;
                    writeln!(file, "    mov {}, rax", d)?;
                }
            }
            IRInstruction::Mod { dest, src1, src2 } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", s1)?;
                writeln!(file, "    cqo")?;
                writeln!(file, "    mov rbx, {}", s2)?;
                writeln!(file, "    idiv rbx")?;
                writeln!(file, "    mov {}, rdx", d)?;
            }
            IRInstruction::CmpEq { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    ucomisd xmm0, xmm1")?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cmp rax, {}", s2)?;
                }
                writeln!(file, "    sete al")?;
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::CmpNeq { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    ucomisd xmm0, xmm1")?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cmp rax, {}", s2)?;
                }
                writeln!(file, "    setne al")?;
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::CmpLt { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    ucomisd xmm1, xmm0")?;
                    writeln!(file, "    seta al")?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cmp rax, {}", s2)?;
                    writeln!(file, "    setl al")?;
                }
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::CmpLte { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    ucomisd xmm1, xmm0")?;
                    writeln!(file, "    setae al")?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cmp rax, {}", s2)?;
                    writeln!(file, "    setle al")?;
                }
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::CmpGt { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    ucomisd xmm0, xmm1")?;
                    writeln!(file, "    seta al")?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cmp rax, {}", s2)?;
                    writeln!(file, "    setg al")?;
                }
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::CmpGte { dest, src1, src2, is_float } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if *is_float {
                    writeln!(file, "    movq xmm0, {}", s1)?;
                    writeln!(file, "    movq xmm1, {}", s2)?;
                    writeln!(file, "    ucomisd xmm0, xmm1")?;
                    writeln!(file, "    setae al")?;
                } else {
                    writeln!(file, "    mov rax, {}", s1)?;
                    writeln!(file, "    cmp rax, {}", s2)?;
                    writeln!(file, "    setge al")?;
                }
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::LogAnd { dest, src1, src2 } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", s1)?;
                writeln!(file, "    and rax, {}", s2)?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::LogOr { dest, src1, src2 } => {
                let s1 = Self::mem_loc(&format!("reg_{}", src1), stack_map);
                let s2 = Self::mem_loc(&format!("reg_{}", src2), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", s1)?;
                writeln!(file, "    or rax, {}", s2)?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::LogNot { dest, src } => {
                let s = Self::mem_loc(&format!("reg_{}", src), stack_map);
                let d = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", s)?;
                writeln!(file, "    test rax, rax")?;
                writeln!(file, "    sete al")?;
                writeln!(file, "    movzx rax, al")?;
                writeln!(file, "    mov {}, rax", d)?;
            }
            IRInstruction::Label(label) => {
                writeln!(file, "{}:", label)?;
            }
            IRInstruction::Jump(label) => {
                writeln!(file, "    jmp {}", label)?;
            }
            IRInstruction::JumpIfFalse { cond_reg, label } => {
                let cond_loc = Self::mem_loc(&format!("reg_{}", cond_reg), stack_map);
                writeln!(file, "    mov rax, {}", cond_loc)?;
                writeln!(file, "    test rax, rax")?;
                writeln!(file, "    jz {}", label)?;
            }
            IRInstruction::Emit { reg, reg_type } => {
                let loc = Self::mem_loc(&format!("reg_{}", reg), stack_map);
                match reg_type {
                    Type::Num => {
                        writeln!(file, "    movq xmm0, {}", loc)?;
                        writeln!(file, "    call print_double")?;
                    }
                    Type::Int => {
                        writeln!(file, "    mov rcx, {}", loc)?;
                        writeln!(file, "    call print_int")?;
                    }
                    Type::Flag => {
                        writeln!(file, "    mov rcx, {}", loc)?;
                        writeln!(file, "    call print_bool")?;
                    }
                    Type::Text => {
                        writeln!(file, "    mov rcx, {}", loc)?;
                        writeln!(file, "    call print_string")?;
                    }
                    _ => {
                        writeln!(file, "    mov rcx, {}", loc)?;
                        writeln!(file, "    call print_int")?;
                    }
                }
            }
            IRInstruction::Call { dest, name, args } => {
                let win64_int_regs = ["rcx", "rdx", "r8", "r9"];
                for (idx, arg_reg) in args.iter().enumerate() {
                    if idx < 4 {
                        let arg_loc = Self::mem_loc(&format!("reg_{}", arg_reg), stack_map);
                        writeln!(file, "    mov {}, {}", win64_int_regs[idx], arg_loc)?;
                    }
                }
                writeln!(file, "    sub rsp, 32")?;
                writeln!(file, "    call {}", name)?;
                writeln!(file, "    add rsp, 32")?;
                if let Some(d) = dest {
                    let d_loc = Self::mem_loc(&format!("reg_{}", d), stack_map);
                    writeln!(file, "    mov {}, rax", d_loc)?;
                }
            }
            IRInstruction::Yield(reg) => {
                if let Some(r) = reg {
                    let r_loc = Self::mem_loc(&format!("reg_{}", r), stack_map);
                    writeln!(file, "    mov rax, {}", r_loc)?;
                }
                writeln!(file, "    mov rsp, rbp")?;
                writeln!(file, "    pop rbp")?;
                writeln!(file, "    ret")?;
            }
            IRInstruction::ComputeAddr { dest, var_name } => {
                let d_loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                if let Some(map) = stack_map {
                    if let Some(offset) = map.get(&format!("var_{}", var_name)) {
                        writeln!(file, "    lea rax, [rbp - {}]", offset)?;
                        writeln!(file, "    mov {}, rax", d_loc)?;
                        return Ok(());
                    }
                }
                writeln!(file, "    lea rax, [var_{}]", var_name)?;
                writeln!(file, "    mov {}, rax", d_loc)?;
            }
            IRInstruction::LoadDeref { dest, ptr_reg } => {
                let p_loc = Self::mem_loc(&format!("reg_{}", ptr_reg), stack_map);
                let d_loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", p_loc)?;
                writeln!(file, "    mov rbx, [rax]")?;
                writeln!(file, "    mov {}, rbx", d_loc)?;
            }
            IRInstruction::StoreDeref { ptr_reg, val_reg } => {
                let p_loc = Self::mem_loc(&format!("reg_{}", ptr_reg), stack_map);
                let v_loc = Self::mem_loc(&format!("reg_{}", val_reg), stack_map);
                writeln!(file, "    mov rax, {}", p_loc)?;
                writeln!(file, "    mov rbx, {}", v_loc)?;
                writeln!(file, "    mov [rax], rbx")?;
            }
            IRInstruction::ComputeFieldAddr { dest, base_reg, byte_offset } => {
                let b_loc = Self::mem_loc(&format!("reg_{}", base_reg), stack_map);
                let d_loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", b_loc)?;
                writeln!(file, "    add rax, {}", byte_offset)?;
                writeln!(file, "    mov {}, rax", d_loc)?;
            }
            IRInstruction::ComputeIndexAddr { dest, base_reg, index_reg, elem_size } => {
                let b_loc = Self::mem_loc(&format!("reg_{}", base_reg), stack_map);
                let i_loc = Self::mem_loc(&format!("reg_{}", index_reg), stack_map);
                let d_loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    mov rax, {}", b_loc)?;
                writeln!(file, "    mov rbx, {}", i_loc)?;
                writeln!(file, "    imul rbx, {}", elem_size)?;
                writeln!(file, "    add rax, rbx")?;
                writeln!(file, "    mov {}, rax", d_loc)?;
            }
            IRInstruction::Alloc { dest, size_reg } => {
                let s_loc = Self::mem_loc(&format!("reg_{}", size_reg), stack_map);
                let d_loc = Self::mem_loc(&format!("reg_{}", dest), stack_map);
                writeln!(file, "    ; claim(size) -> kernel32!HeapAlloc")?;
                writeln!(file, "    sub rsp, 40")?;
                writeln!(file, "    call GetProcessHeap")?;
                writeln!(file, "    mov rcx, rax")?;
                writeln!(file, "    mov rdx, 8")?;
                writeln!(file, "    mov r8, {}", s_loc)?;
                writeln!(file, "    call HeapAlloc")?;
                writeln!(file, "    add rsp, 40")?;
                writeln!(file, "    mov {}, rax", d_loc)?;
            }
            IRInstruction::Free { ptr_reg } => {
                let p_loc = Self::mem_loc(&format!("reg_{}", ptr_reg), stack_map);
                writeln!(file, "    ; purge(ptr) -> kernel32!HeapFree")?;
                writeln!(file, "    mov r8, {}", p_loc)?;
                writeln!(file, "    sub rsp, 40")?;
                writeln!(file, "    call GetProcessHeap")?;
                writeln!(file, "    mov rcx, rax")?;
                writeln!(file, "    xor rdx, rdx")?;
                writeln!(file, "    call HeapFree")?;
                writeln!(file, "    add rsp, 40")?;
            }
        }
        Ok(())
    }

    fn collect_global_symbols(&self, program: &IRProgram) -> (BTreeSet<usize>, BTreeSet<String>) {
        let mut registers = BTreeSet::new();
        let mut variables = BTreeSet::new();
        self.inspect_instructions(&program.main_instructions, &mut registers, &mut variables);
        (registers, variables)
    }

    fn collect_local_symbols(&self, instructions: &[IRInstruction]) -> (BTreeSet<usize>, BTreeSet<String>) {
        let mut registers = BTreeSet::new();
        let mut variables = BTreeSet::new();
        self.inspect_instructions(instructions, &mut registers, &mut variables);
        (registers, variables)
    }

    fn inspect_instructions(
        &self,
        instructions: &[IRInstruction],
        registers: &mut BTreeSet<usize>,
        variables: &mut BTreeSet<String>,
    ) {
        for ins in instructions {
            match ins {
                IRInstruction::LoadFloatConst { dest, .. }
                | IRInstruction::LoadIntConst { dest, .. }
                | IRInstruction::LoadStringConst { dest, .. }
                | IRInstruction::LoadBoolConst { dest, .. } => {
                    registers.insert(*dest);
                }
                IRInstruction::LoadVar { dest, name } => {
                    registers.insert(*dest);
                    variables.insert(name.clone());
                }
                IRInstruction::StoreVar { name, src } => {
                    registers.insert(*src);
                    variables.insert(name.clone());
                }
                IRInstruction::Add { dest, src1, src2, .. }
                | IRInstruction::Sub { dest, src1, src2, .. }
                | IRInstruction::Mul { dest, src1, src2, .. }
                | IRInstruction::Div { dest, src1, src2, .. }
                | IRInstruction::CmpEq { dest, src1, src2, .. }
                | IRInstruction::CmpNeq { dest, src1, src2, .. }
                | IRInstruction::CmpLt { dest, src1, src2, .. }
                | IRInstruction::CmpLte { dest, src1, src2, .. }
                | IRInstruction::CmpGt { dest, src1, src2, .. }
                | IRInstruction::CmpGte { dest, src1, src2, .. }
                | IRInstruction::LogAnd { dest, src1, src2 }
                | IRInstruction::LogOr { dest, src1, src2 }
                | IRInstruction::Mod { dest, src1, src2 } => {
                    registers.insert(*dest);
                    registers.insert(*src1);
                    registers.insert(*src2);
                }
                IRInstruction::LogNot { dest, src } => {
                    registers.insert(*dest);
                    registers.insert(*src);
                }
                IRInstruction::Emit { reg, .. } => {
                    registers.insert(*reg);
                }
                IRInstruction::JumpIfFalse { cond_reg, .. } => {
                    registers.insert(*cond_reg);
                }
                IRInstruction::Call { dest, args, .. } => {
                    if let Some(d) = dest {
                        registers.insert(*d);
                    }
                    for a in args {
                        registers.insert(*a);
                    }
                }
                IRInstruction::Yield(reg) => {
                    if let Some(r) = reg {
                        registers.insert(*r);
                    }
                }
                IRInstruction::ComputeAddr { dest, var_name } => {
                    registers.insert(*dest);
                    variables.insert(var_name.clone());
                }
                IRInstruction::LoadDeref { dest, ptr_reg } => {
                    registers.insert(*dest);
                    registers.insert(*ptr_reg);
                }
                IRInstruction::StoreDeref { ptr_reg, val_reg } => {
                    registers.insert(*ptr_reg);
                    registers.insert(*val_reg);
                }
                IRInstruction::ComputeFieldAddr { dest, base_reg, .. } => {
                    registers.insert(*dest);
                    registers.insert(*base_reg);
                }
                IRInstruction::ComputeIndexAddr { dest, base_reg, index_reg, .. } => {
                    registers.insert(*dest);
                    registers.insert(*base_reg);
                    registers.insert(*index_reg);
                }
                IRInstruction::Alloc { dest, size_reg } => {
                    registers.insert(*dest);
                    registers.insert(*size_reg);
                }
                IRInstruction::Free { ptr_reg } => {
                    registers.insert(*ptr_reg);
                }
                _ => {}
            }
        }
    }

    fn emit_runtime_formatters(&self, file: &mut File) -> io::Result<()> {
        writeln!(file, "; --- Freestanding Console I/O Runtime ---")?;

        // 1. print_crlf: Writes CRLF (\r\n) to console
        writeln!(file, "print_crlf:")?;
        writeln!(file, "    push rbp")?;
        writeln!(file, "    mov rbp, rsp")?;
        writeln!(file, "    sub rsp, 48")?;
        writeln!(file, "    mov ecx, -11       ; STD_OUTPUT_HANDLE")?;
        writeln!(file, "    call GetStdHandle")?;
        writeln!(file, "    mov rcx, rax")?;
        writeln!(file, "    lea rdx, [crlf]")?;
        writeln!(file, "    mov r8, 2")?;
        writeln!(file, "    lea r9, [bytes_written]")?;
        writeln!(file, "    mov qword [rsp + 32], 0")?;
        writeln!(file, "    call WriteFile")?;
        writeln!(file, "    add rsp, 48")?;
        writeln!(file, "    pop rbp")?;
        writeln!(file, "    ret")?;
        writeln!(file)?;

        // 2. print_string: Prints string + automatic CRLF newline
        writeln!(file, "print_string:")?;
        writeln!(file, "    push rbp")?;
        writeln!(file, "    mov rbp, rsp")?;
        writeln!(file, "    push rbx")?;
        writeln!(file, "    push r12")?;
        writeln!(file, "    sub rsp, 48")?;
        writeln!(file, "    mov rbx, rcx")?;
        writeln!(file, "    xor r12, r12")?;
        writeln!(file, ".str_len_loop:")?;
        writeln!(file, "    cmp byte [rbx + r12], 0")?;
        writeln!(file, "    je .str_len_done")?;
        writeln!(file, "    inc r12")?;
        writeln!(file, "    jmp .str_len_loop")?;
        writeln!(file, ".str_len_done:")?;
        writeln!(file, "    mov ecx, -11       ; STD_OUTPUT_HANDLE")?;
        writeln!(file, "    call GetStdHandle")?;
        writeln!(file, "    mov rcx, rax")?;
        writeln!(file, "    mov rdx, rbx")?;
        writeln!(file, "    mov r8, r12")?;
        writeln!(file, "    lea r9, [bytes_written]")?;
        writeln!(file, "    mov qword [rsp + 32], 0")?;
        writeln!(file, "    call WriteFile")?;
        writeln!(file, "    call print_crlf")?;
        writeln!(file, "    add rsp, 48")?;
        writeln!(file, "    pop r12")?;
        writeln!(file, "    pop rbx")?;
        writeln!(file, "    pop rbp")?;
        writeln!(file, "    ret")?;
        writeln!(file)?;

        // 3. print_bool
        writeln!(file, "print_bool:")?;
        writeln!(file, "    test rcx, rcx")?;
        writeln!(file, "    jz .print_b_false")?;
        writeln!(file, "    lea rcx, [str_true]")?;
        writeln!(file, "    jmp print_string")?;
        writeln!(file, ".print_b_false:")?;
        writeln!(file, "    lea rcx, [str_false]")?;
        writeln!(file, "    jmp print_string")?;
        writeln!(file)?;

        // 4. print_int
        writeln!(file, "print_int:")?;
        writeln!(file, "    push rbp")?;
        writeln!(file, "    mov rbp, rsp")?;
        writeln!(file, "    sub rsp, 64")?;
        writeln!(file, "    lea rdi, [rbp - 1]")?;
        writeln!(file, "    mov byte [rdi], 0")?;
        writeln!(file, "    mov rax, rcx")?;
        writeln!(file, "    xor r8d, r8d")?;
        writeln!(file, "    cmp rax, 0")?;
        writeln!(file, "    jge .p_pos")?;
        writeln!(file, "    neg rax")?;
        writeln!(file, "    mov r8b, 1")?;
        writeln!(file, ".p_pos:")?;
        writeln!(file, "    mov rbx, 10")?;
        writeln!(file, ".p_loop:")?;
        writeln!(file, "    xor rdx, rdx")?;
        writeln!(file, "    div rbx")?;
        writeln!(file, "    add dl, '0'")?;
        writeln!(file, "    dec rdi")?;
        writeln!(file, "    mov [rdi], dl")?;
        writeln!(file, "    test rax, rax")?;
        writeln!(file, "    jnz .p_loop")?;
        writeln!(file, "    test r8b, r8b")?;
        writeln!(file, "    jz .p_done")?;
        writeln!(file, "    dec rdi")?;
        writeln!(file, "    mov byte [rdi], '-'")?;
        writeln!(file, ".p_done:")?;
        writeln!(file, "    mov rcx, rdi")?;
        writeln!(file, "    call print_string")?;
        writeln!(file, "    add rsp, 64")?;
        writeln!(file, "    pop rbp")?;
        writeln!(file, "    ret")?;
        writeln!(file)?;

        // 5. print_double
        writeln!(file, "print_double:")?;
        writeln!(file, "    push rbp")?;
        writeln!(file, "    mov rbp, rsp")?;
        writeln!(file, "    sub rsp, 48")?;
        writeln!(file, "    cvttsd2si rax, xmm0")?;
        writeln!(file, "    mov rcx, rax")?;
        writeln!(file, "    call print_int")?;
        writeln!(file, "    add rsp, 48")?;
        writeln!(file, "    pop rbp")?;
        writeln!(file, "    ret")?;
        writeln!(file)?;

        Ok(())
    }
}